-- Migration 010: Seed all 84 projects

INSERT INTO projects (name) VALUES
  ('DigiEdit Language (Books)'),
  ('DigiEdit Language (Journals)'),
  ('Language Editing'),
  ('Language Quality Score'),
  ('Language Errors Count'),
  ('PPT Generator'),
  ('Content Creation'),
  ('Image Comparision tool'),
  ('DEI'),
  ('Meta Data Extraction'),
  ('Synthetic Data Generation'),
  ('Alt Text (JSON and ZIP)'),
  ('Alt Text (IDTF)'),
  ('Alt Text (EPUB)'),
  ('Sematic Search Bot'),
  ('Alt Text (single image)'),
  ('Actual Text'),
  ('Story Board Assistance'),
  ('Proof Reading'),
  ('Abstract and Keywords'),
  ('Spell Check'),
  ('Speech to Text Recognition'),
  ('AI Assessment Creation'),
  ('PDF chatbot'),
  ('Image relabelling'),
  ('Simple Language Summary'),
  ('Summary generation'),
  ('Highwire Chatbot'),
  ('Image Processing'),
  ('Image Forensics'),
  ('AI QC'),
  ('Translation(Extraction)'),
  ('Translation(Import)'),
  ('Image upscaling'),
  ('Image generator'),
  ('Language Translation'),
  ('Taxonomy'),
  ('Email Sentiment Analysis'),
  ('Chatbot response labelling'),
  ('XML Heading Hierarchy'),
  ('XML Element Prediction'),
  ('Grammar Check (C&G)'),
  ('Grammar Check (C&G) - Word'),
  ('Grammar Check (C&G) - XML'),
  ('Language Translation'),
  ('Edition Evolution Analyzer'),
  ('Knowledge_Graph'),
  ('AI XML Processing'),
  ('FM Structuring'),
  ('Bibliography Structuring'),
  ('Story board creation'),
  ('Edit Optimization'),
  ('JSON Translation'),
  ('HTML Conversion'),
  ('eMFC XML Rule Report Generation'),
  ('TOC Extractor'),
  ('MultiModal Alt Text'),
  ('Docx Alt text Generation'),
  ('DEI Image Check'),
  ('Peer Reviewer Finding'),
  ('Language Translation(D)'),
  ('Indexing'),
  ('Database Chat (Text2SQL)'),
  ('XML(QC)'),
  ('Image processing Dashboard'),
  ('Element Prediction Dashboard'),
  ('Alt Text Dashboard (M1)'),
  ('ALT TEXT DASHBOARD (E)'),
  ('Alt-Text Dashboard (M2)'),
  ('Lewis A/B Testing'),
  ('Data Labelling Dashboard'),
  ('Lewis Review Dashboard'),
  ('Classification Accuracy Dashboard'),
  ('Classification (T)'),
  ('Peer Review Critique'),
  ('Gen AI - Email Assistant'),
  ('Chatbot Assistant'),
  ('Gen AI-Image Analytics'),
  ('Gen AI - Papers to Audio'),
  ('Scientific Illustration Generator'),
  ('Gen AI - Voice audit System'),
  ('GenAI Anonymization Tool'),
  ('AI Content Detector'),
  ('TandF Rubriq proessing'),
  ('TandF LAT Score for tracks')
ON CONFLICT (name) DO NOTHING;
