-- Migration 024b: Populate error_detail for the 29 tables missing from 024

-- Alt_Text_(IDTF)
UPDATE "Alt_Text_(IDTF)" SET error_detail = E'Traceback (most recent call last):\n  File "idtf_parser.py", line 28, in parse\n    tree = idtf_reader.load(filepath)\n  File "idtf_reader.py", line 44, in load\n    raise IDTFParseError("IDTF parse failed: file structure is not valid IDTF format")\nIDTFParseError: IDTF parse failed — file ''alt_text_idtf_07.idtf'' does not conform to IDTF specification. Header magic bytes missing or corrupted.' WHERE error = 'IDTF parse failed' AND error_detail IS NULL;

UPDATE "Alt_Text_(IDTF)" SET error_detail = E'Traceback (most recent call last):\n  File "idtf_alt_text.py", line 55, in validate_schema\n    xmlschema.validate(idtf_xml, schema_file)\nxmlschema.exceptions.XMLSchemaValidationError: Schema mismatch — IDTF element ''<alt-text-block>'' at line 18 is not valid under schema version 2.0. Expected schema version 2.1 or higher.' WHERE error = 'Schema mismatch' AND error_detail IS NULL;

UPDATE "Alt_Text_(IDTF)" SET error_detail = E'Traceback (most recent call last):\n  File "idtf_alt_text.py", line 77, in generate\n    result = await asyncio.wait_for(vision_model.describe(image), timeout=30.0)\nasyncio.TimeoutError: Timeout — IDTF alt text generation did not complete within 30 seconds for image embedded in IDTF file at offset 4096.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Alt_Text_(JSON_and_ZIP)
UPDATE "Alt_Text_(JSON_and_ZIP)" SET error_detail = E'Traceback (most recent call last):\n  File "json_zip_alt_text.py", line 33, in extract\n    images = extractor.extract_from_zip(zip_path)\n  File "zip_extractor.py", line 55, in extract_from_zip\n    raise ExtractionError("Extraction error: ZIP archive contains no image entries")\nExtractionError: Extraction error — ZIP archive ''assets_bundle_03.zip'' contains 0 image files. Expected at least 1 PNG or JPG entry.' WHERE error = 'Extraction error' AND error_detail IS NULL;

UPDATE "Alt_Text_(JSON_and_ZIP)" SET error_detail = E'Traceback (most recent call last):\n  File "json_zip_alt_text.py", line 22, in load_manifest\n    manifest = json.loads(manifest_content)\njson.JSONDecodeError: JSON invalid — Expecting property name enclosed in double quotes at line 7 column 3 (char 188). Manifest JSON file contains trailing comma or comment.' WHERE error = 'JSON invalid' AND error_detail IS NULL;

UPDATE "Alt_Text_(JSON_and_ZIP)" SET error_detail = E'Traceback (most recent call last):\n  File "json_zip_alt_text.py", line 18, in open_archive\n    zf = zipfile.ZipFile(zip_path, ''r'')\n  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__\n    raise BadZipFile("File is not a zip file")\nzipfile.BadZipFile: Zip unreadable — file ''images_export.zip'' is not a valid ZIP archive. File may be corrupted or have an incorrect extension.' WHERE error = 'Zip unreadable' AND error_detail IS NULL;

-- Alt_Text_(single_image)
UPDATE "Alt_Text_(single_image)" SET error_detail = E'Traceback (most recent call last):\n  File "single_image_alt.py", line 44, in generate_caption\n    caption = caption_model.predict(image_tensor)\n  File "caption_model.py", line 66, in predict\n    raise CaptionError("Caption failed: model returned empty caption string")\nCaptionError: Caption failed — image captioning model returned an empty string for image ''single_img_14.png''. Image may be blank or contain only whitespace.' WHERE error = 'Caption failed' AND error_detail IS NULL;

UPDATE "Alt_Text_(single_image)" SET error_detail = E'Traceback (most recent call last):\n  File "single_image_alt.py", line 55, in validate_ocr\n    assert ocr_text == expected_text, f"OCR mismatch: got {ocr_text!r}, expected {expected_text!r}"\nAssertionError: OCR mismatch — OCR extracted text ''Flgure 3'' does not match expected text ''Figure 3''. OCR model may be misreading low-resolution or rotated text.' WHERE error = 'OCR mismatch' AND error_detail IS NULL;

-- Content_Creation
UPDATE "Content_Creation" SET error_detail = E'Traceback (most recent call last):\n  File "content_creator.py", line 44, in generate\n    content = llm.generate(prompt)\n  File "llm_client.py", line 77, in generate\n    raise AIGenerationError("AI generation failed: LLM returned empty content")\nAIGenerationError: AI generation failed — LLM returned an empty string for content generation request. Model may have hit a content policy filter or context limit.' WHERE error = 'AI generation failed' AND error_detail IS NULL;

UPDATE "Content_Creation" SET error_detail = E'Traceback (most recent call last):\n  File "content_creator.py", line 28, in validate_format\n    schema.validate(content_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: content payload does not match expected schema")\nInvalidFormatError: Invalid format — content payload field ''content_type'' has value ''video'' which is not in allowed set {''article'', ''blog'', ''summary'', ''abstract''}.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "Content_Creation" SET error_detail = E'Traceback (most recent call last):\n  File "content_creator.py", line 88, in create\n    result = await asyncio.wait_for(generate_content(brief), timeout=60.0)\nasyncio.TimeoutError: Timeout error — content creation pipeline did not complete within 60 seconds. Brief length: 2400 words. LLM endpoint may be experiencing high latency.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- DEI
UPDATE "DEI" SET error_detail = E'Traceback (most recent call last):\n  File "dei_analyzer.py", line 38, in check_bias\n    result = bias_model.analyze(content)\n  File "bias_model.py", line 55, in analyze\n    raise BiasDetectionError("Bias detection failed: model returned inconclusive result")\nBiasDetectionError: Bias detection failed — DEI bias model returned inconclusive result for document ''dei_review_08.pdf''. Model confidence 0.29 is below minimum threshold 0.60.' WHERE error = 'Bias detection failed' AND error_detail IS NULL;

UPDATE "DEI" SET error_detail = E'Traceback (most recent call last):\n  File "dei_analyzer.py", line 22, in validate_input\n    schema.validate(input_payload)\n  File "format_validator.py", line 29, in validate\n    raise InvalidFormatError("Invalid format: DEI input payload missing required field")\nInvalidFormatError: Invalid format — DEI analysis input is missing required field ''document_type''. Accepted types: article, image, video_transcript.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "DEI" SET error_detail = E'Traceback (most recent call last):\n  File "dei_analyzer.py", line 55, in parse_document\n    text = document_parser.extract_text(filepath)\n  File "document_parser.py", line 44, in extract_text\n    raise ParseError("Parsing failed: document parser returned empty text")\nParseError: Parsing failed — document parser returned empty text for file ''dei_doc_11.docx''. File may be password-protected or contain only images.' WHERE error = 'Parsing failed' AND error_detail IS NULL;

UPDATE "DEI" SET error_detail = E'Traceback (most recent call last):\n  File "dei_analyzer.py", line 77, in analyze\n    result = await asyncio.wait_for(run_dei_check(doc), timeout=45.0)\nasyncio.TimeoutError: Timeout error — DEI analysis did not complete within 45 seconds. Document has 180 pages. Consider splitting into smaller sections.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- DigiEdit_Language_(Books)
UPDATE "DigiEdit_Language_(Books)" SET error_detail = E'Traceback (most recent call last):\n  File "digiedit_books.py", line 28, in validate_format\n    schema.validate(book_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: book payload does not match DigiEdit schema")\nInvalidFormatError: Invalid format — book payload field ''isbn'' is not a valid ISBN-13. Received: ''978-0-000-00000-X'' (invalid check digit).' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "DigiEdit_Language_(Books)" SET error_detail = E'Traceback (most recent call last):\n  File "digiedit_books.py", line 55, in parse_content\n    text = book_parser.extract(filepath)\n  File "book_parser.py", line 44, in extract\n    raise ParseError("Parsing failed: book parser could not extract text from file")\nParseError: Parsing failed — book parser returned empty content for ''chapter_03.xml''. File may be malformed or use an unsupported XML dialect.' WHERE error = 'Parsing failed' AND error_detail IS NULL;

UPDATE "DigiEdit_Language_(Books)" SET error_detail = E'Traceback (most recent call last):\n  File "digiedit_books.py", line 88, in process\n    result = await asyncio.wait_for(language_edit(book), timeout=90.0)\nasyncio.TimeoutError: Timeout error — DigiEdit language processing for book did not complete within 90 seconds. Book has 420 pages.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- DigiEdit_Language_(Journals)
UPDATE "DigiEdit_Language_(Journals)" SET error_detail = E'Traceback (most recent call last):\n  File "digiedit_journals.py", line 28, in validate_format\n    schema.validate(journal_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: journal payload missing required field ''doi''")\nInvalidFormatError: Invalid format — journal article payload is missing the required ''doi'' field. All journal articles must have a valid DOI before processing.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "DigiEdit_Language_(Journals)" SET error_detail = E'Traceback (most recent call last):\n  File "digiedit_journals.py", line 55, in parse_article\n    text = article_parser.extract(filepath)\n  File "article_parser.py", line 44, in extract\n    raise ParseError("Parsing failed: article parser returned empty text")\nParseError: Parsing failed — article parser returned empty text for ''journal_article_07.xml''. File may contain only figures and tables with no body text.' WHERE error = 'Parsing failed' AND error_detail IS NULL;

UPDATE "DigiEdit_Language_(Journals)" SET error_detail = E'Traceback (most recent call last):\n  File "digiedit_journals.py", line 88, in process\n    result = await asyncio.wait_for(language_edit(article), timeout=60.0)\nasyncio.TimeoutError: Timeout error — DigiEdit journal language processing did not complete within 60 seconds. Article has 12,000 words.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- Highwire_Chatbot
UPDATE "Highwire_Chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "highwire_chatbot.py", line 44, in call_api\n    response = requests.post(HIGHWIRE_API_URL, json=payload, timeout=20)\n  File "api_client.py", line 38, in handle_response\n    raise APIFailedError("API failed: Highwire API returned HTTP 503")\nAPIFailedError: API failed — Highwire API returned HTTP 503 Service Unavailable. The upstream service may be down for maintenance.' WHERE error = 'API failed' AND error_detail IS NULL;

UPDATE "Highwire_Chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "highwire_chatbot.py", line 33, in chunk_document\n    chunks = chunker.split(document_text, chunk_size=512)\n  File "text_chunker.py", line 55, in split\n    raise ChunkError("Chunk failed: document chunker returned empty chunk list")\nChunkError: Chunk failed — text chunker returned 0 chunks for document of 8400 characters. Minimum chunk size may be larger than the document.' WHERE error = 'Chunk failed' AND error_detail IS NULL;

UPDATE "Highwire_Chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "highwire_chatbot.py", line 55, in embed_chunks\n    embeddings = embedding_model.encode(chunks)\n  File "embedding_model.py", line 44, in encode\n    raise EmbeddingError("Embedding failed: embedding model returned null vector")\nEmbeddingError: Embedding failed — embedding model returned a null vector for chunk at index 7. Chunk may contain only whitespace or special characters.' WHERE error = 'Embedding failed' AND error_detail IS NULL;

UPDATE "Highwire_Chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "highwire_chatbot.py", line 88, in respond\n    result = await asyncio.wait_for(generate_response(query), timeout=25.0)\nasyncio.TimeoutError: Timeout — Highwire chatbot response generation did not complete within 25 seconds. Vector search and LLM call combined exceeded time limit.' WHERE error = 'Timeout' AND error_detail IS NULL;

UPDATE "Highwire_Chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "highwire_chatbot.py", line 66, in search_vectors\n    results = vector_store.search(query_embedding, top_k=5)\n  File "vector_store.py", line 38, in search\n    raise VectorStoreError("Vector issue: vector store returned inconsistent similarity scores")\nVectorStoreError: Vector issue — vector store returned similarity scores outside valid range [0.0, 1.0]. Index may be corrupted. Re-index the document corpus.' WHERE error = 'Vector issue' AND error_detail IS NULL;

-- Image_Comparision_tool
UPDATE "Image_Comparision_tool" SET error_detail = E'Traceback (most recent call last):\n  File "image_comparison.py", line 28, in validate_input\n    schema.validate(comparison_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: comparison payload missing ''image_b'' field")\nInvalidFormatError: Invalid format — image comparison request is missing required field ''image_b''. Both ''image_a'' and ''image_b'' must be provided for comparison.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "Image_Comparision_tool" SET error_detail = E'Traceback (most recent call last):\n  File "image_comparison.py", line 55, in compare\n    diff = comparator.compute_diff(img_a, img_b)\n  File "image_comparator.py", line 77, in compute_diff\n    raise MismatchError("Mismatch detected: images have different dimensions and cannot be compared")\nMismatchError: Mismatch detected — image_a is 1920x1080 but image_b is 1280x720. Images must have identical dimensions for pixel-level comparison.' WHERE error = 'Mismatch detected' AND error_detail IS NULL;

UPDATE "Image_Comparision_tool" SET error_detail = E'Traceback (most recent call last):\n  File "image_comparison.py", line 88, in run_comparison\n    result = await asyncio.wait_for(full_comparison(img_a, img_b), timeout=40.0)\nasyncio.TimeoutError: Timeout error — image comparison did not complete within 40 seconds. Images are 8K resolution (7680x4320). Consider downscaling before comparison.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- Image_Processing
UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 44, in detect_blur\n    score = blur_detector.score(image)\n  File "blur_detector.py", line 33, in score\n    raise BlurDetectionError("Blur detection failed: Laplacian variance computation returned NaN")\nBlurDetectionError: Blur detection failed — Laplacian variance returned NaN for image ''proc_img_03.png''. Image may be entirely uniform (solid color).' WHERE error = 'Blur detection failed' AND error_detail IS NULL;

UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 18, in load_image\n    img_data = decode_image_bytes(raw_bytes)\n  File "image_decoder.py", line 31, in decode_image_bytes\n    raise CorruptImageError("Corrupt image: image data failed integrity check")\nCorruptImageError: Corrupt image — image file ''proc_img_11.jpg'' failed JPEG integrity check. EOI marker not found. File may have been truncated during upload.' WHERE error = 'Corrupt image' AND error_detail IS NULL;

UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 55, in apply_filter\n    filtered = filter_engine.apply(image, filter_name)\n  File "filter_engine.py", line 44, in apply\n    raise FilterError("Filter failed: filter engine returned null output for filter ''{filter_name}''")\nFilterError: Filter failed — filter engine returned null output for filter ''sharpen_v2''. Filter definition may be missing or the filter kernel is invalid.' WHERE error = 'Filter failed' AND error_detail IS NULL;

UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 66, in run_ocr\n    text = ocr_engine.extract(image)\n  File "ocr_engine.py", line 55, in extract\n    raise OCRMismatchError("OCR mismatch: extracted text confidence below threshold")\nOCRMismatchError: OCR mismatch — extracted text confidence 0.42 is below required threshold 0.75 for image ''proc_img_19.png''. Image may have low contrast or unusual font.' WHERE error = 'OCR mismatch' AND error_detail IS NULL;

UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 33, in resize\n    resized = cv2.resize(img, (target_w, target_h))\n  File "image_processor.py", line 38, in validate_resize\n    raise ResizeError("Resize failed: target dimensions are zero or negative")\nResizeError: Resize failed — target dimensions (0, 480) are invalid. Width must be greater than 0. Check the resize configuration parameters.' WHERE error = 'Resize failed' AND error_detail IS NULL;

UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 77, in segment\n    mask = segmentation_model.predict(image_tensor)\n  File "segmentation_model.py", line 66, in predict\n    raise SegmentationError("Segmentation failed: model returned empty mask")\nSegmentationError: Segmentation failed — segmentation model returned an empty mask for image ''proc_img_27.png''. Image may not contain any recognizable objects.' WHERE error = 'Segmentation failed' AND error_detail IS NULL;

UPDATE "Image_Processing" SET error_detail = E'Traceback (most recent call last):\n  File "image_processor.py", line 99, in process\n    result = await asyncio.wait_for(full_pipeline(image), timeout=45.0)\nasyncio.TimeoutError: Timeout — image processing pipeline did not complete within 45 seconds. Image size: 24 MP. Consider reducing resolution before processing.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Image_relabelling
UPDATE "Image_relabelling" SET error_detail = E'Traceback (most recent call last):\n  File "image_relabeller.py", line 44, in validate_label\n    assert predicted != existing, f"Label mismatch: predicted ''{predicted}'' same as existing ''{existing}''"\nAssertionError: Label mismatch — predicted label ''cat'' conflicts with existing label ''dog'' for image_id=8821. Manual review required before relabelling.' WHERE error = 'Label mismatch' AND error_detail IS NULL;

UPDATE "Image_relabelling" SET error_detail = E'Traceback (most recent call last):\n  File "image_relabeller.py", line 33, in run_ocr\n    text = ocr_engine.extract(image)\n  File "ocr_engine.py", line 44, in extract\n    raise OCRError("OCR failed: OCR engine returned empty text for image")\nOCRError: OCR failed — OCR engine returned empty text for image ''relabel_img_07.png''. Image may not contain any readable text or may be too blurry for OCR.' WHERE error = 'OCR failed' AND error_detail IS NULL;

UPDATE "Image_relabelling" SET error_detail = E'Traceback (most recent call last):\n  File "image_relabeller.py", line 77, in relabel\n    result = await asyncio.wait_for(classify_and_relabel(image), timeout=30.0)\nasyncio.TimeoutError: Timeout — image relabelling did not complete within 30 seconds. Classification model may be overloaded.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Language_Editing
UPDATE "Language_Editing" SET error_detail = E'Traceback (most recent call last):\n  File "language_editor.py", line 44, in check_grammar\n    corrections = grammar_engine.check(text)\n  File "grammar_engine.py", line 66, in check\n    raise GrammarError("Grammar failed: grammar engine returned null correction list")\nGrammarError: Grammar failed — grammar engine returned null for input text of 3200 words. Engine may have encountered an unsupported language construct or dialect.' WHERE error = 'Grammar failed' AND error_detail IS NULL;

UPDATE "Language_Editing" SET error_detail = E'Traceback (most recent call last):\n  File "language_editor.py", line 28, in validate_format\n    schema.validate(edit_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: language editing payload missing ''language'' field")\nInvalidFormatError: Invalid format — language editing request is missing required field ''language''. Supported languages: en, fr, de, es, ja, zh.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "Language_Editing" SET error_detail = E'Traceback (most recent call last):\n  File "language_editor.py", line 88, in edit\n    result = await asyncio.wait_for(run_language_edit(doc), timeout=60.0)\nasyncio.TimeoutError: Timeout error — language editing did not complete within 60 seconds. Document has 15,000 words. Consider processing in smaller chunks.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- Language_Errors_Count
UPDATE "Language_Errors_Count" SET error_detail = E'Traceback (most recent call last):\n  File "error_counter.py", line 44, in count_errors\n    assert actual_count == expected_count, f"Count mismatch: got {actual_count}, expected {expected_count}"\nAssertionError: Count mismatch — error counter returned 142 errors but validation expects 138. Duplicate error entries may exist in the source document.' WHERE error = 'Count mismatch' AND error_detail IS NULL;

UPDATE "Language_Errors_Count" SET error_detail = E'Traceback (most recent call last):\n  File "error_counter.py", line 28, in validate_input\n    schema.validate(count_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: error count payload missing ''document_id'' field")\nInvalidFormatError: Invalid format — language error count request is missing required field ''document_id''. Cannot associate error count without a document identifier.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "Language_Errors_Count" SET error_detail = E'Traceback (most recent call last):\n  File "error_counter.py", line 77, in count\n    result = await asyncio.wait_for(run_error_count(doc), timeout=40.0)\nasyncio.TimeoutError: Timeout error — language error counting did not complete within 40 seconds. Document has 22,000 words.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- Language_Quality_Score
UPDATE "Language_Quality_Score" SET error_detail = E'Traceback (most recent call last):\n  File "quality_scorer.py", line 28, in validate_input\n    schema.validate(score_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: quality score payload missing ''target_language'' field")\nInvalidFormatError: Invalid format — language quality score request is missing required field ''target_language''. Cannot compute quality score without specifying the target language.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "Language_Quality_Score" SET error_detail = E'Traceback (most recent call last):\n  File "quality_scorer.py", line 55, in compute_score\n    score = scoring_engine.evaluate(source_text, target_text)\n  File "scoring_engine.py", line 77, in evaluate\n    raise ScoringEngineError("Score engine failed: scoring model returned NaN score")\nScoringEngineError: Score engine failed — language quality scoring model returned NaN for document pair. Source or target text may contain only special characters or be empty.' WHERE error = 'Score engine failed' AND error_detail IS NULL;

UPDATE "Language_Quality_Score" SET error_detail = E'Traceback (most recent call last):\n  File "quality_scorer.py", line 88, in score\n    result = await asyncio.wait_for(run_quality_score(doc_pair), timeout=50.0)\nasyncio.TimeoutError: Timeout error — language quality scoring did not complete within 50 seconds. Document pair has combined 18,000 words.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- Meta_Data_Extraction
UPDATE "Meta_Data_Extraction" SET error_detail = E'Traceback (most recent call last):\n  File "metadata_extractor.py", line 18, in open_file\n    doc = file_reader.open(filepath)\n  File "file_reader.py", line 33, in open\n    raise CorruptFileError("Corrupt file: file reader could not open document")\nCorruptFileError: Corrupt file — file reader failed to open ''metadata_doc_09.pdf''. File may be password-protected, truncated, or have an invalid PDF structure.' WHERE error = 'Corrupt file' AND error_detail IS NULL;

UPDATE "Meta_Data_Extraction" SET error_detail = E'Traceback (most recent call last):\n  File "metadata_extractor.py", line 77, in extract\n    result = await asyncio.wait_for(run_extraction(doc), timeout=35.0)\nasyncio.TimeoutError: Timeout — metadata extraction did not complete within 35 seconds. Document has 600 pages with complex embedded metadata.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- PDF_chatbot
UPDATE "PDF_chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "pdf_chatbot.py", line 33, in chunk_pdf\n    chunks = pdf_chunker.split(pdf_text, chunk_size=512)\n  File "pdf_chunker.py", line 44, in split\n    raise ChunkingError("Chunking error: PDF chunker failed to split document into valid chunks")\nChunkingError: Chunking error — PDF chunker returned 0 valid chunks for ''report_q3.pdf''. Document may be a scanned image-only PDF with no extractable text.' WHERE error = 'Chunking error' AND error_detail IS NULL;

UPDATE "PDF_chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "pdf_chatbot.py", line 55, in embed_chunks\n    embeddings = embedding_model.encode(chunks)\n  File "embedding_model.py", line 44, in encode\n    raise EmbeddingError("Embedding failed: embedding model returned null vector for chunk")\nEmbeddingError: Embedding failed — embedding model returned a null vector for PDF chunk at index 12. Chunk may contain only page numbers or headers.' WHERE error = 'Embedding failed' AND error_detail IS NULL;

UPDATE "PDF_chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "pdf_chatbot.py", line 88, in answer_query\n    result = await asyncio.wait_for(retrieve_and_generate(query), timeout=30.0)\nasyncio.TimeoutError: Timeout — PDF chatbot query processing did not complete within 30 seconds. Vector search and LLM generation combined exceeded time limit.' WHERE error = 'Timeout' AND error_detail IS NULL;

UPDATE "PDF_chatbot" SET error_detail = E'Traceback (most recent call last):\n  File "pdf_chatbot.py", line 66, in store_vectors\n    vector_store.upsert(embeddings, metadata)\n  File "vector_store.py", line 38, in upsert\n    raise VectorStoreError("Vector error: vector store upsert failed due to dimension mismatch")\nVectorStoreError: Vector error — embedding dimension 1536 does not match vector store index dimension 768. Re-create the index with the correct embedding dimension.' WHERE error = 'Vector error' AND error_detail IS NULL;

-- PPT_Generator
UPDATE "PPT_Generator" SET error_detail = E'Traceback (most recent call last):\n  File "ppt_generator.py", line 28, in validate_input\n    schema.validate(ppt_payload)\n  File "format_validator.py", line 33, in validate\n    raise InvalidFormatError("Invalid format: PPT payload missing required field ''slide_count''")\nInvalidFormatError: Invalid format — PPT generation request is missing required field ''slide_count''. Must specify number of slides between 1 and 50.' WHERE error = 'Invalid format' AND error_detail IS NULL;

UPDATE "PPT_Generator" SET error_detail = E'Traceback (most recent call last):\n  File "ppt_generator.py", line 55, in generate_slides\n    slide = slide_renderer.render(slide_data)\n  File "slide_renderer.py", line 77, in render\n    raise SlideGenerationError("Slide generation failed: template engine returned null for slide")\nSlideGenerationError: Slide generation failed — template engine returned null for slide index 4. Slide data may contain an unsupported content block type ''interactive_chart''.' WHERE error = 'Slide generation failed' AND error_detail IS NULL;

UPDATE "PPT_Generator" SET error_detail = E'Traceback (most recent call last):\n  File "ppt_generator.py", line 88, in generate\n    result = await asyncio.wait_for(build_presentation(brief), timeout=60.0)\nasyncio.TimeoutError: Timeout error — PPT generation did not complete within 60 seconds. Presentation has 35 slides with embedded charts and images.' WHERE error = 'Timeout error' AND error_detail IS NULL;

-- Proof_Reading
UPDATE "Proof_Reading" SET error_detail = E'Traceback (most recent call last):\n  File "proof_reader.py", line 44, in run_grammar_check\n    corrections = grammar_engine.check(text)\n  File "grammar_engine.py", line 66, in check\n    raise GrammarEngineError("Grammar engine failed: engine returned null correction list")\nGrammarEngineError: Grammar engine failed — grammar engine returned null for document ''proof_doc_05.docx'' of 6800 words. Engine may have crashed or timed out internally.' WHERE error = 'Grammar engine failed' AND error_detail IS NULL;

UPDATE "Proof_Reading" SET error_detail = E'Traceback (most recent call last):\n  File "proof_reader.py", line 33, in detect_language\n    lang = language_detector.detect(text)\n  File "language_detector.py", line 28, in detect\n    raise LanguageMismatchError("Language mismatch: detected language differs from declared language")\nLanguageMismatchError: Language mismatch — detected language ''fr'' (French) does not match declared language ''en'' (English). Verify document language before proofreading.' WHERE error = 'Language mismatch' AND error_detail IS NULL;

-- Sematic_Search_Bot
UPDATE "Sematic_Search_Bot" SET error_detail = E'Traceback (most recent call last):\n  File "semantic_search.py", line 55, in embed_query\n    embedding = embedding_model.encode(query_text)\n  File "embedding_model.py", line 44, in encode\n    raise EmbeddingError("Embedding failed: embedding model returned null vector for query")\nEmbeddingError: Embedding failed — embedding model returned a null vector for query ''what is the refund policy?''. Query may contain only stop words or special characters.' WHERE error = 'Embedding failed' AND error_detail IS NULL;

UPDATE "Sematic_Search_Bot" SET error_detail = E'Traceback (most recent call last):\n  File "semantic_search.py", line 66, in search_index\n    results = search_index.query(query_embedding, top_k=10)\n  File "search_index.py", line 38, in query\n    raise IndexError("Index error: search index is not initialized or has been corrupted")\nIndexError: Index error — semantic search index is not initialized. Run index build before performing search queries.' WHERE error = 'Index error' AND error_detail IS NULL;

UPDATE "Sematic_Search_Bot" SET error_detail = E'Traceback (most recent call last):\n  File "semantic_search.py", line 88, in search\n    result = await asyncio.wait_for(embed_and_search(query), timeout=15.0)\nasyncio.TimeoutError: Timeout — semantic search did not complete within 15 seconds. Vector index may be too large or the embedding model is slow.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Simple_Language_Summary
UPDATE "Simple_Language_Summary" SET error_detail = E'Traceback (most recent call last):\n  File "simple_summary.py", line 55, in simplify\n    simplified = simplifier.process(sentence)\n  File "text_simplifier.py", line 44, in process\n    raise ComplexSentenceError("Complex sentence issue: sentence exceeds maximum complexity score")\nComplexSentenceError: Complex sentence issue — sentence at paragraph 8 has Flesch-Kincaid grade level 18.2, exceeding maximum allowed 12.0. Manual simplification required.' WHERE error = 'Complex sentence issue' AND error_detail IS NULL;

UPDATE "Simple_Language_Summary" SET error_detail = E'Traceback (most recent call last):\n  File "simple_summary.py", line 22, in validate_input\n    if len(input_text.split()) < MIN_WORDS:\n      raise InputTooShortError(f"Input too short: {word_count} words, minimum is {MIN_WORDS}")\nInputTooShortError: Input too short — input text has only 12 words, minimum required for summarization is 50 words.' WHERE error = 'Input too short' AND error_detail IS NULL;

UPDATE "Simple_Language_Summary" SET error_detail = E'Traceback (most recent call last):\n  File "simple_summary.py", line 44, in call_language_model\n    response = language_model.generate(prompt)\n  File "language_model.py", line 66, in generate\n    raise LanguageModelError("Language model failed: model returned empty output")\nLanguageModelError: Language model failed — language simplification model returned empty output for input of 1200 words. Model may have hit a content filter.' WHERE error = 'Language model failed' AND error_detail IS NULL;

UPDATE "Simple_Language_Summary" SET error_detail = E'Traceback (most recent call last):\n  File "simple_summary.py", line 66, in summarize\n    summary = summarizer.generate(text)\n  File "summarizer.py", line 55, in generate\n    raise SummaryError("Summary failed: summarizer returned empty summary")\nSummaryError: Summary failed — summarizer returned an empty string for document of 4500 words. LLM may have refused the request or the document is in an unsupported language.' WHERE error = 'Summary failed' AND error_detail IS NULL;

UPDATE "Simple_Language_Summary" SET error_detail = E'Traceback (most recent call last):\n  File "simple_summary.py", line 88, in process\n    result = await asyncio.wait_for(simplify_and_summarize(doc), timeout=45.0)\nasyncio.TimeoutError: Timeout — simple language summarization did not complete within 45 seconds. Document has 9000 words.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Speech_to_Text_Recognition
UPDATE "Speech_to_Text_Recognition" SET error_detail = E'Traceback (most recent call last):\n  File "speech_to_text.py", line 44, in transcribe\n    transcript = asr_model.transcribe(audio_data)\n  File "asr_model.py", line 66, in transcribe\n    raise AudioUnclearError("Audio unclear: ASR model confidence below threshold")\nAudioUnclearError: Audio unclear — ASR model confidence 0.38 is below required threshold 0.70 for audio file ''recording_07.wav''. Audio may have heavy background noise or mumbled speech.' WHERE error = 'Audio unclear' AND error_detail IS NULL;

UPDATE "Speech_to_Text_Recognition" SET error_detail = E'Traceback (most recent call last):\n  File "speech_to_text.py", line 33, in preprocess_audio\n    clean_audio = noise_reducer.reduce(audio_data)\n  File "noise_reducer.py", line 44, in reduce\n    raise NoiseDetectedError("Noise detected: audio SNR below minimum threshold")\nNoiseDetectedError: Noise detected — audio signal-to-noise ratio 8.2 dB is below minimum required 15 dB. Apply noise reduction before transcription.' WHERE error = 'Noise detected' AND error_detail IS NULL;

UPDATE "Speech_to_Text_Recognition" SET error_detail = E'Traceback (most recent call last):\n  File "speech_to_text.py", line 88, in recognize\n    result = await asyncio.wait_for(asr_pipeline(audio), timeout=60.0)\nasyncio.TimeoutError: Timeout — speech-to-text recognition did not complete within 60 seconds. Audio file is 45 minutes long. Consider splitting into shorter segments.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Spell_Check
UPDATE "Spell_Check" SET error_detail = E'Traceback (most recent call last):\n  File "spell_checker.py", line 44, in check\n    corrections = spell_engine.check(text, dictionary=dictionary)\n  File "spell_engine.py", line 55, in check\n    raise DictionaryError("Dictionary error: spell check dictionary failed to load")\nDictionaryError: Dictionary error — spell check dictionary for locale ''en_GB'' failed to load from ''/usr/share/hunspell/en_GB.dic''. File may be missing or corrupted.' WHERE error = 'Dictionary error' AND error_detail IS NULL;

UPDATE "Spell_Check" SET error_detail = E'Traceback (most recent call last):\n  File "spell_checker.py", line 28, in read_document\n    text = document_bytes.decode(encoding)\nUnicodeDecodeError: Encoding failed — ''utf-8'' codec can''t decode byte 0x8d in position 1024. Document may be encoded in Windows-1252 or Latin-1. Specify encoding explicitly.' WHERE error = 'Encoding failed' AND error_detail IS NULL;

UPDATE "Spell_Check" SET error_detail = E'Traceback (most recent call last):\n  File "spell_checker.py", line 33, in load_language_pack\n    pack = language_pack_registry.get(language_code)\n  File "language_pack_registry.py", line 19, in get\n    raise LanguagePackMissingError(f"Language pack missing for ''{language_code}''")\nLanguagePackMissingError: Language pack missing — no spell check language pack found for ''cy'' (Welsh). Install the Welsh language pack before running spell check.' WHERE error = 'Language pack missing' AND error_detail IS NULL;

UPDATE "Spell_Check" SET error_detail = E'Traceback (most recent call last):\n  File "spell_checker.py", line 88, in run_check\n    result = await asyncio.wait_for(full_spell_check(doc), timeout=30.0)\nasyncio.TimeoutError: Timeout — spell check did not complete within 30 seconds. Document has 25,000 words with many technical terms.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Story_Board_Assistance
UPDATE "Story_Board_Assistance" SET error_detail = E'Traceback (most recent call last):\n  File "storyboard_assist.py", line 55, in generate_frame\n    frame = frame_generator.generate(scene_data)\n  File "frame_generator.py", line 77, in generate\n    raise FrameGenerationError("Frame generation failed: generator returned null frame")\nFrameGenerationError: Frame generation failed — frame generator returned null for scene ''scene_04_climax''. Scene data may contain unsupported visual element type ''3d_model''.' WHERE error = 'Frame generation failed' AND error_detail IS NULL;

UPDATE "Story_Board_Assistance" SET error_detail = E'Traceback (most recent call last):\n  File "storyboard_assist.py", line 33, in load_slide\n    slide = slide_loader.load(slide_path)\n  File "slide_loader.py", line 28, in load\n    raise SlideCorruptError("Slide corrupt: slide file failed integrity check")\nSlideCorruptError: Slide corrupt — slide file ''storyboard_slide_07.pptx'' failed integrity check. File may have been corrupted during upload or transfer.' WHERE error = 'Slide corrupt' AND error_detail IS NULL;

UPDATE "Story_Board_Assistance" SET error_detail = E'Traceback (most recent call last):\n  File "storyboard_assist.py", line 22, in load_template\n    template = template_store.get(template_id)\n  File "template_store.py", line 19, in get\n    raise TemplateError("Template error: storyboard template not found in registry")\nTemplateError: Template error — storyboard template ''cinematic_v3'' not found in template registry. Available templates: basic, corporate, cinematic_v1, cinematic_v2.' WHERE error = 'Template error' AND error_detail IS NULL;

UPDATE "Story_Board_Assistance" SET error_detail = E'Traceback (most recent call last):\n  File "storyboard_assist.py", line 88, in assist\n    result = await asyncio.wait_for(generate_storyboard(brief), timeout=90.0)\nasyncio.TimeoutError: Timeout — storyboard assistance did not complete within 90 seconds. Brief has 12 scenes with complex visual descriptions.' WHERE error = 'Timeout' AND error_detail IS NULL;

-- Summary_generation
UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 28, in validate_format\n    schema.validate(summary_payload)\n  File "format_validator.py", line 33, in validate\n    raise FormatMismatchError("Format mismatch: summary payload does not match expected schema")\nFormatMismatchError: Format mismatch — summary payload field ''output_format'' has value ''markdown'' but pipeline expects ''plain_text''. Convert output format before submission.' WHERE error = 'Format mismatch' AND error_detail IS NULL;

UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 18, in load_document\n    doc = document_loader.load(filepath)\n  File "document_loader.py", line 33, in load\n    raise InputCorruptError("Input corrupt: document loader returned empty content")\nInputCorruptError: Input corrupt — document loader returned empty content for ''summary_input_04.pdf''. File may be a scanned image-only PDF or have no extractable text.' WHERE error = 'Input corrupt' AND error_detail IS NULL;

UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 44, in load_model\n    model = SummaryModel.load(MODEL_PATH)\n  File "summary_model.py", line 14, in load\n    raise ModelUnavailableError("Model unavailable: summary model checkpoint not found")\nModelUnavailableError: Model unavailable — summary model checkpoint ''/models/summarizer_v4.pt'' not found. Ensure the model is downloaded before running summary generation.' WHERE error = 'Model unavailable' AND error_detail IS NULL;

UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 66, in generate\n    summary = summarizer.generate(text)\n  File "summarizer.py", line 55, in generate\n    raise SummaryEngineError("Summary engine failed: summarizer returned empty output")\nSummaryEngineError: Summary engine failed — summarizer returned an empty string for document of 5200 words. LLM may have refused the request or hit a content filter.' WHERE error = 'Summary engine failed' AND error_detail IS NULL;

UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 88, in summarize\n    result = await asyncio.wait_for(run_summary(doc), timeout=50.0)\nasyncio.TimeoutError: Timeout — summary generation did not complete within 50 seconds. Document has 12,000 words.' WHERE error = 'Timeout' AND error_detail IS NULL;

UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 55, in call_llm\n    response = openai.ChatCompletion.create(model="gpt-4", messages=messages)\nopenai.error.InvalidRequestError: Token overflow — maximum context length is 8192 tokens. Summary generation prompt resulted in 12,400 tokens. Split document into smaller sections.' WHERE error = 'Token overflow' AND error_detail IS NULL;

UPDATE "Summary_generation" SET error_detail = E'Traceback (most recent call last):\n  File "summary_generator.py", line 99, in handle_response\n    raise UnknownError(f"Unknown error: unexpected exception during summary generation")\nUnknownError: Unknown error — an unexpected exception occurred during summary generation for document_id=''doc_0441''. Check application logs for full stack trace.' WHERE error = 'Unknown error' AND error_detail IS NULL;

-- Synthetic_Data_Generation
UPDATE "Synthetic_Data_Generation" SET error_detail = E'Traceback (most recent call last):\n  File "synthetic_data_gen.py", line 28, in validate_schema\n    schema.validate(output_data)\n  File "format_validator.py", line 33, in validate\n    raise FormatMismatchError("Format mismatch: generated data does not match target schema")\nFormatMismatchError: Format mismatch — generated synthetic data field ''age'' has type ''str'' but target schema expects ''int''. Check the data generation template configuration.' WHERE error = 'Format mismatch' AND error_detail IS NULL;

UPDATE "Synthetic_Data_Generation" SET error_detail = E'Traceback (most recent call last):\n  File "synthetic_data_gen.py", line 55, in generate\n    data = generator.generate(schema, n_samples=1000)\n  File "data_generator.py", line 77, in generate\n    raise GeneratorError("Generator failed: data generator returned empty dataset")\nGeneratorError: Generator failed — synthetic data generator returned 0 samples for schema ''customer_profile_v2''. Generator configuration may have conflicting constraints.' WHERE error = 'Generator failed' AND error_detail IS NULL;

UPDATE "Synthetic_Data_Generation" SET error_detail = E'Traceback (most recent call last):\n  File "synthetic_data_gen.py", line 33, in initialize_seed\n    rng = np.random.default_rng(seed_value)\n  File "seed_manager.py", line 22, in validate_seed\n    raise SeedError("Seed error: seed value is not a valid integer")\nSeedError: Seed error — seed value ''auto_timestamp_xyz'' is not a valid integer seed. Provide a numeric seed value for reproducible data generation.' WHERE error = 'Seed error' AND error_detail IS NULL;
